version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host}:{port in Container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_DB: testdb
    networks:
      - nestjs-network #de cung dia chi ip
networks:
  nestjs-network:
# docker compose up -d
# xoa
# docker compose down
# docker compose up -d dev-database -d
# docker logs fadee4899b00
